#!/usr/bin/env php
<?php

if ($argv[1] === 'start') {
    $firstName = readline("Your first name: ");
    $lastName = readline("Your last name: ");
    print_r("\nHello $firstName $lastName\n\n");
    print_r("
 __        __            _         _     _____       _               _        _                                                       _   
 \ \      / /___   __ _ | |  ___  | |_  |_   _|__ _ | |  ___  _ __  | |_     / \    ___  ___   ___  ___  ___  _ __ ___    ___  _ __  | |___
  \ \ /\ / // _ \ / _` || | / _ \ | __|   | | / _` || | / _ \| \'_ \ | __|  / _ \  / __|/ __| / _ \/ __|/ __|| \'_ ` _ \  / _ \| \'_ \ | __|
   \ V  V /|  __/| (_| || || (_) || |_    | || (_| || ||  __/| | | || |_   / ___ \ \__ \\__ \|  __/\__ \\__ \| | | | | ||  __/| | | || |_ 
    \_/\_/  \___| \__, ||_| \___/  \__|   |_| \__,_||_| \___||_| |_| \__| /_/   \_\|___/|___/ \___||___/|___/|_| |_| |_| \___||_| |_| \__|
                  |___/                                                                                                                   
\n");
    exec('php composer.phar install');
    exec("git branch $firstName-$lastName");
    exec("git checkout $firstName-$lastName");
    exec('git add .');
    exec('git commit -m "Started talent assessment"');
}

if ($argv[1] === 'finish') {
    print_r('todo');
}

