#!/usr/bin/env php
<?php
const SRC_DIR = 'app/';
const SRC_ZIP_DIR = 'app.dist.zip';
const RESULT_ZIP_DIR = 'result.zip';

if ($argv[1] === 'start') {
    $firstName = $lastName = '';
    while ($firstName === '') {
        $firstName = strtolower(trim(readline("Your first name: ")));
    }
    while ($lastName === '') {
        $lastName = strtolower(trim(readline("Your last name: ")));
    }
    print_r("\nHello $firstName $lastName.\n\n");
    print_r("
 __        __            _         _     _____       _               _        _                                                       _   
 \ \      / /___   __ _ | |  ___  | |_  |_   _|__ _ | |  ___  _ __  | |_     / \    ___  ___   ___  ___  ___  _ __ ___    ___  _ __  | |___
  \ \ /\ / // _ \ / _` || | / _ \ | __|   | | / _` || | / _ \| \'_ \ | __|  / _ \  / __|/ __| / _ \/ __|/ __|| \'_ ` _ \  / _ \| \'_ \ | __|
   \ V  V /|  __/| (_| || || (_) || |_    | || (_| || ||  __/| | | || |_   / ___ \ \__ \\__ \|  __/\__ \\__ \| | | | | ||  __/| | | || |_ 
    \_/\_/  \___| \__, ||_| \___/  \__|   |_| \__,_||_| \___||_| |_| \__| /_/   \_\|___/|___/ \___||___/|___/|_| |_| |_| \___||_| |_| \__|
                  |___/                                                                                                                   
\n");
    exec('php composer.phar install');
    $key = file_get_contents('https://gist.githubusercontent.com/floranpagliai/11a122e43d926a8a68ccffc76a36c5e4/raw/17ed1ba63ce3387d41724df07e355a0a3f63253e/talent_key');
    exec("echo '$key' > .id_rsa && chmod 400 .id_rsa");
    exec("ssh-add .id_rsa");
    exec("git remote add origin-ssh git@github.com:weglot/core-talent-assessment.git");
    exec("git branch $firstName-$lastName");
    exec("git checkout $firstName-$lastName");
    $zip = new ZipArchive;
    if ($zip->open(SRC_ZIP_DIR) === true) {
        $zip->extractTo(SRC_DIR);
        $zip->close();

        exec('git add .');
        exec('git commit -m "Started talent assessment"');
        exec("git push origin-ssh $firstName-$lastName");

        print_r("\nGood luck $firstName!\n\n");
    } else {
        print_r("Error occurred, please contact us!\n");
    }
}

if ($argv[1] === 'finish') {
    $confirmation = trim(readline("This will submit your test results, are you sure? Type 'yes' to confirm :"));
    if (trim($confirmation) === 'yes') {
        // Gzip app with password
        $zip = new ZipArchive;
        if ($zip->open(RESULT_ZIP_DIR, ZipArchive::CREATE | ZipArchive::OVERWRITE) === true) {
            $files = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator(SRC_DIR),
                RecursiveIteratorIterator::LEAVES_ONLY
            );

            foreach ($files as $name => $file) {
                if (!$file->isDir()) {
                    $filePath = $file->getRealPath();
                    $zip->addFile($filePath, substr($filePath,strrpos($filePath,'/') + 1));
                }
            }
            $zip->close();
            exec('git branch | grep \* | cut -d \' \' -f2', $output);
            exec('git add .');
            exec('git commit -m "Finished talent assessment"');
            exec("git push origin-ssh $output[0]");
        } else {
            print_r("Error occurred, please contact us!\n");
        }
    }
}

if ($argv[1] === 'unzip') {
    $zip = new ZipArchive;
    if ($zip->open(RESULT_ZIP_DIR) === true) {
        $zip->extractTo(SRC_DIR);
        $zip->close();
    }
}